services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    networks:
      - external-network
    command: ["java", "-jar", "app.jar"]

networks:
  external-network:
    external: true






