services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: vendas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vendas-network

  spring-app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_DATABASE: vendas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      - mysql
    networks:
      - vendas-network

networks:
  vendas-network:
    driver: bridge

volumes:
  mysql_data:










