name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin' # Adicione esta linha

      - name: Build with Maven
        run: mvn clean install

      - name: Run Spring Boot Application
        run: |
          java -jar target/vendas-0.0.1-SNAPSHOT.jar &
          sleep 10 # Aguardar o tempo necessário para a aplicação inicializar

      # Adicione etapas para executar testes aqui, se necessário
      - name: Run Integration Tests
        run: mvn test

