name: Docker Compose CI

on:
  push:
    branches:
      - main  # ou a branch que você está usando
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      vendas:
        image: vendas:latest
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        env:
          SPRING_APPLICATION_NAME: vendas
          SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
          SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
          SPRING_DATASOURCE_USERNAME: sa
          SPRING_DATASOURCE_PASSWORD: 123
          SPRING_H2_CONSOLE_ENABLED: true
          SPRING_H2_CONSOLE_PATH: /h2-console
          SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
          SPRING_JPA_SHOW_SQL: true
          SPRING_JPA_HIBERNATE_DDL_AUTO: create

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker-compose build

      - name: Run Docker Compose
        run: docker-compose up -d




